apiVersion: v1
kind: Service
metadata:
  labels:
    servicename: hasher
{{ include "dockercoins_prod.labels" . | indent 4 }}
  name: hasher
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    servicename: hasher
  type: ClusterIP