apiVersion: v1
kind: Endpoints
metadata:
  labels:
    servicename: redis
{{ include "dockercoins_prod.labels" . | indent 4 }}
  name: redis
subsets:
  - addresses:
      - ip: 192.168.33.101
    ports:
      - port: 6379