apiVersion: v1
kind: Service
metadata:
  labels:
    servicename: redis
{{ include "dockercoins_prod.labels" . | indent 4 }}
  name: redis
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379