apiVersion: v1
kind: Service
metadata:
  labels:
    servicename: rng
{{ include "dockercoins_prod.labels" . | indent 4 }}
  name: rng
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    servicename: rng
  type: ClusterIP