{{- if and .Values.serviceName (ne .Values.serviceName "rng") }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  template:
    metadata:
      labels:
{{ include "dockercoins.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.serviceName }}
      {{- if (eq .Values.serviceName "redis") }}
        image: redis
      {{- else }}
        image: {{ .Values.image.registry }}/{{ .Values.serviceName }}:{{ .Values.image.version }}
      {{- end }}
        env:
        - name: PROJECT_NAME
          value: dockercoins
        - name: ENVIRONMENT
          value: {{ .Release.Namespace }}
        - name: SERVICE_NAME
          value: {{ .Values.serviceName }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- if eq .Release.Namespace "uat" }}
      {{- if eq .Values.serviceName "hasher" }}
{{ toYaml .Values.hasher.probes | indent 8 }}
      {{- else if eq .Values.serviceName "redis" }}
{{ toYaml .Values.redis.probes | indent 8 }}
      {{- else if eq .Values.serviceName "webui" }}
{{ toYaml .Values.webui.probes | indent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
