{{- if and .Values.serviceName (eq .Values.serviceName "webui") }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
{{ include "dockercoins.labels" . | indent 4 }}
  name: webui-ingress
spec:
  rules:
  - host: {{.Release.Namespace}}-webui.192.168.33.101.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: webui
          servicePort: 80
{{- end }}
